// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/content.ts
var PROFILE = {
  name: "Santosh Kumar Verma",
  headline: "Full-Stack Developer \xB7 Video Editor & Content Creator",
  location: "India",
  email: "santoshskv2005@gmail.com",
  phone: "+91 73196 62244",
  github: "https://github.com/Santoshverma77",
  instagramCreative: "https://www.instagram.com/_insta.fx_/",
  instagramPersonal: "https://www.instagram.com/santoshverma_77/",
  summary: "Full-stack developer and video editor. BS in Data Science & AI at IIT Madras, building web apps with React/Node and producing cinematic reels, travel films and brand promos."
};
var EDUCATION = [
  {
    institution: "Indian Institute of Technology, Madras",
    credential: "BS, Data Science & Artificial Intelligence",
    period: "Aug 2025 \u2013 Present"
  },
  {
    institution: "S.M. Arya Public School",
    credential: "Class 12th",
    period: "May 2021 \u2013 Jun 2023"
  },
  {
    institution: "Saraswati Shishu Vidya Mandir",
    credential: "Class 8th \u2013 10th",
    period: "Mar 2018 \u2013 Mar 2021"
  }
];
var AWARDS = [
  {
    title: "Logistic Legend Award \u2014 DevFest Ranchi 2025",
    issuer: "Google Developer Group",
    year: "2025"
  },
  {
    title: "Winner \u2014 HACKED 3.0 Hackathon (1st Prize, \u20B925,000)",
    issuer: "BML Munjal University",
    year: "Mar 2025"
  },
  {
    title: "Second Prize \u2014 State-Level Gyan Vigyan Mela",
    issuer: "Vidya Vikas Samiti",
    year: "Oct 2018"
  }
];
var RESUMES = {
  fullstack: {
    label: "Full-Stack Development",
    url: "/resume-fullstack.pdf",
    focus: "Engineering resume: full-stack projects, languages, frameworks, open-source contributions, certifications and community leadership.",
    skills: [
      "React",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "MongoDB",
      "Tailwind CSS",
      "Python",
      "Git & GitHub"
    ]
  },
  video: {
    label: "Video Editing & Creative",
    url: "/resume-video-editing.pdf",
    focus: "Creative resume: video editing, cinematography, motion graphics, content creation and the tools used day to day.",
    skills: [
      "Adobe Premiere Pro",
      "After Effects",
      "DaVinci Resolve",
      "Lightroom",
      "Photoshop",
      "Colour Grading",
      "Sound Design",
      "Cinematography"
    ]
  }
};
var PROJECTS = [
  {
    title: "COOKIE",
    description: "Creative web project with innovative design patterns and interactive cookie-themed UI.",
    link: "https://github.com/Santoshverma77/COOKIE",
    tech: ["HTML", "CSS", "JavaScript"],
    track: "fullstack"
  },
  {
    title: "E-Com Website",
    description: "Full-featured e-commerce platform with product catalog, cart, and responsive UI.",
    link: "https://github.com/Santoshverma77/e-com-website",
    tech: ["React", "Node.js", "MongoDB"],
    track: "fullstack"
  },
  {
    title: "Expense Management",
    description: "Track and manage expenses with an intuitive dashboard, charts, and analytics.",
    link: "https://github.com/Santoshverma77/expense-management-system-main",
    tech: ["JavaScript", "Chart.js", "LocalStorage"],
    track: "fullstack"
  },
  {
    title: "Quizller",
    description: "Interactive quiz application with categories, scoring, and timed challenges.",
    link: "https://github.com/Santoshverma77/Quizller-project",
    tech: ["React", "TypeScript", "Tailwind"],
    track: "fullstack"
  },
  {
    title: "Phishing Detection",
    description: "Browser extension that detects phishing sites with ML and URL analysis.",
    link: "https://github.com/Santoshverma77/phishing-detection-extension",
    tech: ["JavaScript", "ML", "Chrome API"],
    track: "fullstack"
  },
  {
    title: "Tic Tac Toe",
    description: "Classic game with a modern implementation, AI opponent, and clean animations.",
    link: "https://github.com/Santoshverma77/tic_tac_toe_game",
    tech: ["HTML", "CSS", "JavaScript"],
    track: "fullstack"
  },
  {
    title: "Cinematic Travel Reel",
    description: "Story-driven travel edit with beat-matched cuts, speed ramps and cinematic colour grading.",
    link: "https://www.instagram.com/reel/DSBgbC2k66I/",
    tech: ["Premiere Pro", "Colour Grading", "Sound Design"],
    track: "video"
  },
  {
    title: "Portrait & Lifestyle Photography",
    description: "Portrait and lifestyle sets shot and retouched with a warm, filmic look for social delivery.",
    link: "https://www.instagram.com/p/DZUZeGvE_QT/",
    tech: ["Lightroom", "Photoshop", "Retouching"],
    track: "video"
  },
  {
    title: "Promotional Brand Reel",
    description: "Short-form promo cut for a brand launch \u2014 motion titles, product beats, punchy pacing.",
    link: "https://www.instagram.com/reel/DRG6u9lE9Hq/",
    tech: ["After Effects", "Motion Graphics", "Premiere Pro"],
    track: "video"
  },
  {
    title: "Travel Vlog Series",
    description: "Episodic vlog series with location B-roll, voiceover mixing and consistent series grading.",
    link: "https://www.instagram.com/reel/DZ_4y2CzfLa/",
    tech: ["Premiere Pro", "DaVinci Resolve", "Editing"],
    track: "video"
  }
];

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Santosh's profile summary: headline, contact links, education timeline, honors & awards, and the two available resume tracks.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const text = [
      `${PROFILE.name} \u2014 ${PROFILE.headline}`,
      PROFILE.summary,
      "",
      "Education:",
      ...EDUCATION.map((e) => `\u2022 ${e.institution} \u2014 ${e.credential} (${e.period})`),
      "",
      "Honors & Awards:",
      ...AWARDS.map((a) => `\u2022 ${a.title} \u2014 ${a.issuer} (${a.year})`),
      "",
      `Resume tracks: ${Object.values(RESUMES).map((r) => r.label).join(" | ")}`,
      `Links: ${PROFILE.github} \xB7 ${PROFILE.instagramCreative}`,
      `Contact: ${PROFILE.email} \xB7 ${PROFILE.phone}`
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { profile: PROFILE, education: EDUCATION, awards: AWARDS }
    };
  }
});

// src/lib/mcp/tools/get-resume.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var get_resume_default = defineTool2({
  name: "get_resume",
  title: "Get resume",
  description: "Get Santosh's resume details for a track \u2014 'fullstack' (engineering) or 'video' (video editing & creative) \u2014 including focus, key skills and the downloadable PDF path.",
  inputSchema: {
    track: z.enum(["fullstack", "video"]).describe("Which resume track to fetch: fullstack or video.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ track }) => {
    const resume = RESUMES[track];
    const text = [
      `${PROFILE.name} \u2014 ${resume.label}`,
      resume.focus,
      `Key skills: ${resume.skills.join(", ")}`,
      `Resume PDF: ${resume.url}`,
      `Contact: ${PROFILE.email} \xB7 ${PROFILE.phone}`
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { track, ...resume }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "List Santosh's portfolio projects with descriptions, tech/tools and links. Filter by track: 'fullstack' for engineering work, 'video' for video editing & creative work.",
  inputSchema: {
    track: z2.enum(["fullstack", "video", "all"]).default("all").describe("Which work track to list. Defaults to all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ track }) => {
    const selected = !track || track === "all" ? PROJECTS : PROJECTS.filter((p) => p.track === track);
    const text = selected.map(
      (p) => `\u2022 ${p.title} [${p.track}] \u2014 ${p.description}
  Tools: ${p.tech.join(", ")}
  Link: ${p.link}`
    ).join("\n");
    return {
      content: [{ type: "text", text: text || "No projects found for that track." }],
      structuredContent: { projects: selected }
    };
  }
});

// src/lib/mcp/tools/search-portfolio.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_portfolio_default = defineTool4({
  name: "search_portfolio",
  title: "Search portfolio",
  description: "Free-text search across Santosh's projects, skills, education and awards. Use this to answer tailored questions like 'what React work has he done?' or 'what editing tools does he use?'.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Keywords to search for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query.toLowerCase();
    const match = (s) => s.toLowerCase().includes(q);
    const hits = [];
    for (const p of PROJECTS) {
      if (match(p.title) || match(p.description) || p.tech.some(match)) {
        hits.push({
          kind: `project:${p.track}`,
          title: p.title,
          detail: `${p.description} (Tools: ${p.tech.join(", ")})`,
          link: p.link
        });
      }
    }
    for (const [track, r] of Object.entries(RESUMES)) {
      const skills = r.skills.filter(match);
      if (skills.length || match(r.label) || match(r.focus)) {
        hits.push({
          kind: `resume:${track}`,
          title: r.label,
          detail: skills.length ? `Matching skills: ${skills.join(", ")}` : r.focus,
          link: r.url
        });
      }
    }
    for (const e of EDUCATION) {
      if (match(e.institution) || match(e.credential)) {
        hits.push({ kind: "education", title: e.institution, detail: `${e.credential} (${e.period})` });
      }
    }
    for (const a of AWARDS) {
      if (match(a.title) || match(a.issuer)) {
        hits.push({ kind: "award", title: a.title, detail: `${a.issuer} (${a.year})` });
      }
    }
    if (hits.length === 0) {
      return {
        content: [
          {
            type: "text",
            text: `No matches for "${query}". Try get_profile or list_projects for the full picture. Contact: ${PROFILE.email}`
          }
        ],
        structuredContent: { query, hits: [] }
      };
    }
    const text = hits.map((h) => `\u2022 [${h.kind}] ${h.title} \u2014 ${h.detail}${h.link ? `
  Link: ${h.link}` : ""}`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { query, hits }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ncguszbdanzomkbgfzbh";
var mcp_default = defineMcp({
  name: "personal-portfolio",
  title: "Personal Portfolio",
  version: "0.1.0",
  instructions: "Tools for Santosh Kumar Verma's portfolio. Use `get_profile` for a summary, education and awards; `get_resume` for the full-stack or video-editing resume track; `list_projects` for work samples per track; `search_portfolio` for free-text questions about skills, tools and projects. Use these to generate tailored answers (pitches, cover letters, project insights) grounded in this content.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, get_resume_default, list_projects_default, search_portfolio_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
